name: "Pull Request Checks"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: "Validate PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: "Install dependencies"
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install -e ".[dev]"
      
      - name: "Run code quality checks"
        run: |
          source .venv/bin/activate
          # Run ruff for linting and formatting
          ruff check . --output-format=github
          ruff format --check .
          # Run mypy for type checking
          mypy . --install-types --non-interactive
          # Run bandit for security checks
          bandit -r .
      
      - name: "Run tests with coverage"
        run: |
          source .venv/bin/activate
          uv run pytest --cov=pyfinquant --cov-report=xml
      
      - name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          file: "./coverage.xml"
          fail_ci_if_error: true 